services:
  postgres:
    container_name: etl_postgres
    image: postgres:${POSTGRES_VERSION}
    env_file: .env
    hostname: etl_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - sounds_network

  postgres_init:
    build: ./init_db
    container_name: postgres_init
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - sounds_network

networks:
  sounds_network:
    driver: bridge